// Generates incompressible download-test blobs (random bytes defeat every
// compression layer, so wire bytes == file bytes). Output is gitignored and
// regenerated by `prebuild`, so the repo never carries ~144 MB of noise.
import { randomBytes } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';

const COUNT = 6;
const SIZE = 24 * 1024 * 1024; // under the 25 MiB per-file static-asset cap
const CHUNK = 1 << 20;

const dir = new URL('../public/blobs/', import.meta.url);
mkdirSync(dir, { recursive: true });

for (let i = 0; i < COUNT; i++) {
  const parts = [];
  for (let off = 0; off < SIZE; off += CHUNK) parts.push(randomBytes(CHUNK));
  writeFileSync(new URL(`blob-${i}.bin`, dir), Buffer.concat(parts));
}

console.log(`generated ${COUNT} x ${SIZE} bytes in public/blobs/`);
